name: wiyata
version: 0.0.0
github: "zweimach/wiyata.hs"
license: MIT
author: "Ananda Umamil"
maintainer: "zweimach@zweimach.org"
copyright: "2018 Ananda Umamil"
extra-source-files:
  - README.md
  - LICENSE
description: A collection of solutions written in Haskell
dependencies:
  - base
  - containers
  - text
tests:
  wiyata-test:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty
      - tasty-hunit
