name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup GHC
        uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.6.5"

      - name: Setup stack
        uses: mstksg/setup-stack@v1

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build and run tests
        run: stack test --fast --no-terminal --system-ghc
