name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit:
    name: unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version: ["8.8", "8.10", "9.0"]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc-version }}

      - name: Build and run tests
        run: cabal test

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc-version }}
